'use client';

import { Info } from 'lucide-react';
import { useVertical } from '@/context/ai-gov/VerticalContext';
import { Card, CardContent, CardHeader } from '@/components/ai-gov/ui/card';
import { Input } from '@/components/ai-gov/ui/input';
import { Separator } from '@/components/ai-gov/ui/separator';
import { Button } from '@/components/ai-gov/ui/button';
import { Badge } from '@/components/ai-gov/ui/badge';
import type { DisclosureContent } from '@/types/ai-gov';

interface Props {
  notice: DisclosureContent;
}

export function ApplicationPageMock({ notice }: Props) {
  const { vertical } = useVertical();

  return (
    <div className="rounded-lg border bg-white text-zinc-900 shadow-sm dark:bg-zinc-950 dark:text-zinc-100">
      <div className="border-b bg-zinc-50 dark:bg-zinc-900 px-5 py-3 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="h-6 w-6 rounded bg-primary text-primary-foreground grid place-items-center text-xs font-mono">P</div>
          <div className="font-medium">
            {vertical === 'lending' && 'Pinetop FCU — Auto Loan Application'}
            {vertical === 'hr' && 'Pinetop Holdings — Apply: Senior Risk Analyst'}
            {vertical === 'automotive' && 'Pinetop Motors — Aria EV: Pre-Qualify & Enable Connected Services'}
          </div>
        </div>
        <Badge variant="outline" className="text-[10px]">demo only</Badge>
      </div>

      <div className="p-5 space-y-5">
        <Card className="border-primary/40 bg-primary/5">
          <CardHeader className="pb-2">
            <div className="flex items-start gap-2">
              <Info className="h-4 w-4 mt-0.5 text-primary shrink-0" />
              <div>
                <div className="font-semibold text-sm">{notice.pre_decision.headline}</div>
                <div className="text-[10px] uppercase tracking-wider text-muted-foreground mt-0.5">
                  Generated by Instrata · jurisdiction: {notice.jurisdiction}
                </div>
              </div>
            </div>
          </CardHeader>
          <CardContent className="text-sm leading-relaxed space-y-2">
            <p>{notice.pre_decision.body}</p>
            <div className="flex flex-wrap gap-1 pt-1">
              {notice.pre_decision.elements.map((e) => (
                <Badge key={e} variant="secondary" className="text-[10px]">
                  ✓ {e}
                </Badge>
              ))}
            </div>
          </CardContent>
        </Card>

        <Separator />

        {vertical === 'lending' && (
          <div className="grid grid-cols-2 gap-3">
            <Field label="Full legal name" value="Marcus Reyes" />
            <Field label="Date of birth" value="07 / 14 / 1991" />
            <Field label="Annual income" value="$ 74,200" />
            <Field label="Requested amount" value="$ 28,400" />
            <Field label="Term" value="72 months" />
            <Field label="Employer" value="Mesa Logistics LLC" />
          </div>
        )}
        {vertical === 'hr' && (
          <div className="grid grid-cols-2 gap-3">
            <Field label="Full legal name" value="Priya Shah" />
            <Field label="City / state" value="Brooklyn, NY" />
            <Field label="Years of experience" value="6" />
            <Field label="Highest degree" value="B.S. Statistics" />
            <Field label="Current role" value="Senior Analyst, Risk" />
            <Field label="Resume" value="resume_priyashah_2026.pdf" />
          </div>
        )}
        {vertical === 'automotive' && (
          <div className="space-y-3">
            <div className="grid grid-cols-2 gap-3">
              <Field label="Full legal name" value="Karina Velasquez" />
              <Field label="City / state" value="San Diego, CA" />
              <Field label="Vehicle" value="2026 Pinetop Aria EV" />
              <Field label="VIN (pre-allocated)" value="5N1AZ2DJ8RC123456" />
              <Field label="Requested term" value="60 months" />
              <Field label="Trade-in (prior VIN)" value="2021 Pinetop Sentra — 1N4AL3AP5JC987654" />
            </div>
            <div className="rounded-md border bg-muted/30 px-3 py-2 text-xs flex items-start gap-2">
              <input type="checkbox" defaultChecked className="mt-0.5" readOnly />
              <span>
                <span className="font-medium text-foreground">Enable Pinetop Connected Services</span>{' '}
                — predictive maintenance, route optimization, driver-coaching. Telematics is used
                only for the connected services purposes above. Secondary use for financing or
                marketing requires a separate opt-in.
              </span>
            </div>
          </div>
        )}

        <div className="flex items-center justify-between gap-3 pt-2">
          <div className="text-xs text-muted-foreground">
            By submitting, you acknowledge the AI-use notice above.
          </div>
          <Button>
            {vertical === 'lending' && 'Submit application'}
            {vertical === 'hr' && 'Submit candidacy'}
            {vertical === 'automotive' && 'Pre-qualify & continue'}
          </Button>
        </div>
      </div>
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="text-[11px] uppercase tracking-wider text-muted-foreground mb-1">{label}</div>
      <Input value={value} readOnly className="bg-muted/40 cursor-default" />
    </div>
  );
}
